List<String> designationChoices = [
  'University President',
  'Chancellor',
  'Vice Chancellor for Academic Affairs',
  'Vice Chancellor for Research Development and Extension Services',
  'Vice Chancellor for Administration and Finance',
  'Vice Chancellor for Development and External Affairs',
  'Vice President for Academic Affairs',
  'Vice President for Research, Development and Extension Services',
  'Vice President for Administration and Finance',
  'Vice President for Development and External Affairs',
  'Secretary of the University and of the Board of Regents',
  'Director, Legal Affairs',
  'Director, Internal Audit Services',
  'Director, Presidential Project Management',
  'Director, Knowledge, Innovation, Science and Technology (KIST) Park Center',
  'Director, Adaptive Capacity Building and Technology Innovation for Occupational Hazards and Natural Disasters (ACTION) Center',
  'Director, Center for Innovation in Engineering Education (CIEE)',
  'Director, Public Relations Sustainability Development Officer, Center for Sustainable Development',
  'Director, Culture and Arts',
  'Director, Sports Development',
  'Director, Student Affairs and Services',
  'Director, Center for Transformative Learning',
  'Director, Quality Assurance Management',
  'Director, Curriculum and Instruction',
  'Director, Instructional Material Development Center',
  'Director, Mentorship',
  'Director, Research',
  'Director, Research Management',
  'Director, Extension Services',
  'Director, Science, Technology, Engineering and Environment Research (STEER) Hub',
  'Director, Administration Services',
  'Director, Finance Services',
  'Director, Project Management',
  'Director, Health Services',
  'Director, ICT Services',
  'Director, External Affairs',
  'Director, Auxiliary Services',
  'Director, Institutional Planning and Development',
  'OIC – Director for Project Management',
  'Assistant Director, Scholarship',
  'Assistant Director, Testing and Admission',
  'Assistant Director, Services for Students with Special Needs and Persons with Disabilities',
  'Assistant Director, Industry, Energy and Emerging Technology Research',
  'Assistant Director, Agriculture, Aquatic and Natural Resources Research',
  'Assistant Director, Integrated Basic and Applied Research',
  'Assistant Director, Disaster Risk Management and Health Research',
  'Assistant Director, Research Integrity and Assurance',
  'Assistant Director, Research Publication Management',
  'Assistant Director, Knowledge and Technology Transfer Management',
  'Assistant Director, Community Development',
  'Assistant Director, Extension Monitoring and Impact Assessment',
  'Assistant Director, Gender and Development Advocacies',
  'Assistant Director, Human Resource Management',
  'Assistant Director, Procurement',
  'Assistant Director, Property and Supply',
  'Assistant Director, Records Management',
  'Assistant Director, General Services',
  'Assistant Director, Accounting',
  'Assistant Director, Budget',
  'Assistant Director, Cashiering and Disbursement Officer',
  'Assistant Director, Cashiering',
  'Assistant Director, Network and Systems Administration',
  'Assistant Director, ICT Special Projects/ICT Operations',
  'Assistant Director, Management Information System',
  'Assistant Director, Strategic Planning and Performance Measures',
  'Assistant Director, Local Partnership',
  'Disbursing Officer',
  'ISO Focal Person',
  'ISO Lead Auditor',
  'ISO Document Controller',
  'Head, Center for Technopreneurship and Innovation',
  'Head, Electronic Systems Research Center',
  'Head, GIS Applications Development Center',
  'Head, Digital Transformation Center',
  'Head, Manufacturing Research Center',
  'Head, Material Testing and Calibration Center',
  'Head, Analytical Research Center',
  'Head, Food Innovation Center',
  'Head, Social Innovation Research Center',
  'Head, Verde Island Passage Center for Oceanographic Research and Aquatic Life Sciences (VIP CORALS) – Lobo',
  'Head, Verde Island Passage Center for Oceanographic Research and Aquatic Life Sciences (VIP CORALS) – Nasugbu',
  'Head, Internal Audit',
  'Head, Quality Assurance Management',
  'Head, Sustainable Development',
  'Head, General Education',
  'Head, Expanded Tertiary Education Equivalency and Accreditation Program (ETEEAP)',
  'Head, Registration Services',
  'Head, Library Services',
  'Head, Health Services',
  'Head, Testing and Admission',
  'Head, Research, Development and Extension Services',
  'Head, Academic Affairs',
  'Head, Administration and Finance',
  'Head, Development and External Affairs',
  'Head, Administrative Services',
  'Head, Research and Extension',
  'Head, Research and Extension Office',
  'Head, Research Development and Extension Services',
  'Campus Director',
  'Campus Director and Head, Research, Development and Extension Services',
  'Dean (various colleges, e.g., College of Arts and Sciences, College of Accountancy, Business, Economics and International Hospitality Management, College of Teacher Education, College of Health Sciences, College of Law, College of Medicine, College of Criminal Justice Education, College of Industrial Technology, College of Informatics and Computing Sciences)',
  'Associate Dean (various colleges)',
  'Associate Dean & Department Chairman',
  'Department Chairman',
  'Department Chair',
  'Head Teacher III, Integrated School',
  'Head Teacher I, Integrated School-Grade School Department',
  'Head Teacher I, Integrated School- High School Department',
  'Instructor I',
  'Instructor II',
  'Instructor III',
  'Assistant Professor I',
  'Assistant Professor II',
  'Assistant Professor III',
  'Assistant Professor IV',
  'Associate Professor I',
  'Associate Professor III',
  'Associate Professor IV',
  'Associate Professor V',
  'Professor I',
  'Professor V',
  'Professor VI',
  'Teacher I',
  'Lecturer I',
  'Lecturer II',
  'Lecturer III',
  'Lecturer IV',
  'Senior Lecturer I',
];