List<String> officeChoices = [
  'Integrated School',
  'College of Accountancy, Business, Economics, and International Hospitality Management (CABEIHM)',
  'College of Health Sciences',
  'College of Arts and Sciences',
  'College of Law',
  'College of Teacher Education',
  'College of Criminal Justice Education',
  'College of Medicine',
  'College of Engineering',
  'College of Architecture, Fine Arts and Design',
  'College of Industrial Technology',
  'College of Informatics and Computing Sciences',
  'College of Agriculture and Forestry',
  'College of Fisheries and Aquatic Sciences',
  'College of Hospitality Management',
  'College of Business Administration and Accounting Management',
  'College of Marketing Management',
  'College of Management Accounting',
  'College of Technical-Vocational Teacher Education',
  'College of Civil Technology',
  'College of Drafting Technology',
  'College of Electronics Technology',
  'College of Information Technology',
  'College of Development Communication',
];